config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :bankers

  resources :branches

  root 'welcome#index'

  get '/agencies' => 'welcome#agencies'

  get '/dashboard' => 'welcome#dashboard'

  devise_for :clients, controllers: { sessions: 'clients/sessions'}

  resources :clients do
    resources :accounts
   end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :status
  belongs_to :category
  belongs_to :client

end

app/models/banker.rb
class Banker < ActiveRecord::Base
  belongs_to :branch
  has_many :clients

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :bankers

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :client
  belongs_to :account
  belongs_to :status
  belongs_to :type

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :accounts

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :accounts
  has_many :cards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accounts
  has_many :cards

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :cards
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_client!
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  def index
    @accounts = current_client.accounts
    render_with_protection @accounts.to_json
  end

  def show
    render_with_protection @account.to_json
  end

  def new
    @account = Account.new
    render_with_protection @account.json

  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.save
    render_with_protection @account

  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end


  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:beginDate, :expiryDate, :saldo, :rate, :client_id, :status_id, :category_id)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_filter  :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def render_with_protection(json_content, parameters = {})
    render parameters.merge(content_type: 'application/json', text: "\n" + json_content)
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |c|
      c.permit(:email, :password, :password_confirmation, :firstName, :lastName, :street, :streetNr, :zipCode, :city, :birthDate, :birthPlace, :socialSecurityNumber, :nationality, :mobileNumber)
    end
  end
end

app/controllers/bankers_controller.rb
class BankersController < ApplicationController
  before_action :set_banker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bankers = Banker.all
    respond_with(@bankers)
  end

  def show
    respond_with(@banker)
  end

  def new
    @banker = Banker.new
    respond_with(@banker)
  end

  def edit
  end

  def create
    @banker = Banker.new(banker_params)
    @banker.save
    respond_with(@banker)
  end

  def update
    @banker.update(banker_params)
    respond_with(@banker)
  end

  def destroy
    @banker.destroy
    respond_with(@banker)
  end

  private
    def set_banker
      @banker = Banker.find(params[:id])
    end

    def banker_params
      params.require(:banker).permit(:firstName, :lastName, :phoneNumber, :emailAddress, :branch_id)
    end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  def index
    @branches = Branch.all
    render_with_protection @branches.to_json
  end

  def show
    respond_with(@branch)
  end

  def new
    @branch = Branch.new
    respond_with(@branch)
  end

  def edit
  end

  def create
    @branch = Branch.new(branch_params)
    @branch.save
    respond_with(@branch)
  end

  def update
    @branch.update(branch_params)
    respond_with(@branch)
  end

  def destroy
    @branch.destroy
    respond_with(@branch)
  end


  private
    def set_branch
      @branch = Branch.find(params[:id])
    end

    def branch_params
      params.require(:branch).permit(:name, :street, :streetNr, :zipCode, :city)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cards = Card.all
    respond_with(@cards)
  end

  def show
    respond_with(@card)
  end

  def new
    @card = Card.new
    respond_with(@card)
  end

  def edit
  end

  def create
    @card = Card.new(card_params)
    @card.save
    respond_with(@card)
  end

  def update
    @card.update(card_params)
    respond_with(@card)
  end

  def destroy
    @card.destroy
    respond_with(@card)
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:expiryDate, :managingCompany, :saldo, :limit, :client_id, :account_id, :status_id, :type_id)
    end
end

app/controllers/clients/sessions_controller.rb
class Clients::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end



end

app/controllers/clients/unlocks_controller.rb
class Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_client!, except: [:index, :agencies]


  def index
  end

  def agencies
  end

  def dashboard
  end

  private
  def choose_layout
    client_signed_in? ? 'angular' : 'application'
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bankers_helper.rb
module BankersHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/agencies.html.erb
<div class="container-fluid" ng-controller='branchesCtrl'>
  <div class=""col-md-2">
  <p>Search: <span class="glyphicon glyphicon-search"></span></p><input ng-model="query">
  Sort by:
  <select ng-model="orderProp">
    <option value="name">Alphabetical</option>
    <option value="age">Zip Code</option>
  </select>
</div>
<ul>
  <div class="cold-md-10">
    <table class="table">
      <thead>
      <tr>
        <th>Name</th><br>
        <th>Street</th>
        <th>Street Number</th>
        <th>Zip Code</th>
        <th>City</th>
      </tr>
      </thead>
      <tbody ng-repeat="branch in branches | filter:query | orderBy:orderProp">
      <tr class="success"></tr>
      <td>{{ branch.name }}</td>
      <td>{{ branch.street}}</td>
      <td>{{ branch.streetNr }}</td>
      <td>{{ branch.zipCode }}</td>
      <td>{{ branch.city }}</td>
      </tr>
      </tbody>
    </table>
  </div>
</ul>
<%= javascript_include_tag "application" %>
</div>

app/views/welcome/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 col-md-3">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                            </span>Content</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-pencil text-primary"></span><% link_to "Accounts", client_accounts_path %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-flash text-success"></span><a href="#">Cards</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-file text-info"></span><a href="#">Newsletters</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-comment text-success"></span><a href="#">Follow us</a>
                    <span class="badge">42</span>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Preferences</a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Invoices</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Shipments</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Tex</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                            <%= link_to ' Profile', edit_client_registration_path, :class => 'glyphicon glyphicon-user' %>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Change Password</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Import/Export</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                    Delete Account</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                            </span>Reports</a>
            </h4>
          </div>
          <div id="collapseFour" class="panel-collapse collapse">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-9 col-md-9">
      <div class="well">
        <h1>Welcome <strong><%= current_client.firstName %></strong> <strong><%= current_client.lastName %></strong> </h1>

      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div>
  <label>Name:</label>
  <input type="text" ng-model="yourName" placeholder="Enter a name here">
  <hr>
  <h1>Hello {{yourName}}!</h1>
</div>