config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :bankers

  resources :branches

  root 'welcome#index'

  get '/agencies' => 'welcome#agencies'

  get '/dashboard' => 'welcome#dashboard'

  devise_for :clients, controllers: { sessions: 'clients/sessions'}

  resources :clients do
    resources :accounts
   end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :status
  belongs_to :category
  belongs_to :client

end

app/models/banker.rb
class Banker < ActiveRecord::Base
  belongs_to :branch
  has_many :clients

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :bankers

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :client
  belongs_to :account
  belongs_to :status
  belongs_to :type

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :accounts

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :accounts
  has_many :cards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accounts
  has_many :cards

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :cards
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_client!
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  def index
    @accounts = current_client.accounts
    render_with_protection @accounts.to_json
  end

  def show
    render_with_protection @account.to_json
  end

  def new
    @account = Account.new
    render_with_protection @account.json

  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.save
    render_with_protection @account

  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end


  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:beginDate, :expiryDate, :saldo, :rate, :client_id, :status_id, :category_id)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_filter  :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def render_with_protection(json_content, parameters = {})
    render parameters.merge(content_type: 'application/json', text: "\n" + json_content)
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |c|
      c.permit(:email, :password, :password_confirmation, :firstName, :lastName, :street, :streetNr, :zipCode, :city, :birthDate, :birthPlace, :socialSecurityNumber, :nationality, :mobileNumber)
    end
  end
end

app/controllers/bankers_controller.rb
class BankersController < ApplicationController
  before_action :set_banker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bankers = Banker.all
    respond_with(@bankers)
  end

  def show
    respond_with(@banker)
  end

  def new
    @banker = Banker.new
    respond_with(@banker)
  end

  def edit
  end

  def create
    @banker = Banker.new(banker_params)
    @banker.save
    respond_with(@banker)
  end

  def update
    @banker.update(banker_params)
    respond_with(@banker)
  end

  def destroy
    @banker.destroy
    respond_with(@banker)
  end

  private
    def set_banker
      @banker = Banker.find(params[:id])
    end

    def banker_params
      params.require(:banker).permit(:firstName, :lastName, :phoneNumber, :emailAddress, :branch_id)
    end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  def index
    @branches = Branch.all
    render_with_protection @branches.to_json
  end

  def show
    respond_with(@branch)
  end

  def new
    @branch = Branch.new
    respond_with(@branch)
  end

  def edit
  end

  def create
    @branch = Branch.new(branch_params)
    @branch.save
    respond_with(@branch)
  end

  def update
    @branch.update(branch_params)
    respond_with(@branch)
  end

  def destroy
    @branch.destroy
    respond_with(@branch)
  end


  private
    def set_branch
      @branch = Branch.find(params[:id])
    end

    def branch_params
      params.require(:branch).permit(:name, :street, :streetNr, :zipCode, :city)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cards = Card.all
    respond_with(@cards)
  end

  def show
    respond_with(@card)
  end

  def new
    @card = Card.new
    respond_with(@card)
  end

  def edit
  end

  def create
    @card = Card.new(card_params)
    @card.save
    respond_with(@card)
  end

  def update
    @card.update(card_params)
    respond_with(@card)
  end

  def destroy
    @card.destroy
    respond_with(@card)
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:expiryDate, :managingCompany, :saldo, :limit, :client_id, :account_id, :status_id, :type_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_client!, except: [:index, :agencies]


  def index
  end

  def agencies
  end

  def dashboard
  end

  private
  def choose_layout
    client_signed_in? ? 'angular' : 'application'
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bankers_helper.rb
module BankersHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/angular.html.erb
<html lang="en" ng-app="bankApp">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">BankApp</a>
    </div>


    <p class="navbar-text pull-right">
      <% if client_signed_in? %>
          Logged in as <strong><%= current_client.email %></strong>.
          <%= link_to 'Edit profile', edit_client_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_client_session_path,method: :delete, :class => 'navbar-link'  %>
      <% end %>


      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/dashboard">Dashboard</a></li>
        </ul>
      </div>
      </div>
</nav>




</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="bankApp">
<head>
  <title>Online Bank</title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
  <script src="/assets/bankApp.js"></script>

  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>

  <![endif]-->
</head>

<body>
<div class="container">
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

<header class="navbar navbar-fixed-top navbar-inverse">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Online Banking</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li class="active"><a href="/agencies">Agencies</a></li>
          <li class="active"><a href="/dashboard">Dashboard</a></li>
          <% if client_signed_in? %>
            <li class="active"><a href="/accounts">Products</a></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if client_signed_in? %>
              Logged in as <strong><%= current_client.firstName %></strong> <strong><%= current_client.lastName %></strong>.
              <%= link_to 'Edit profile', edit_client_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_client_session_path, method: :delete, :class => 'navbar-link'  %>

          <% else %>
              <span class="glyphicon glyphicon-user"></span><%= link_to "Become Client", new_client_registration_path, :class => 'navbar-link'  %>  |
              <span class="glyphicon glyphicon-user"></span><%= link_to "Login", new_client_session_path, :class => 'navbar-link'  %>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>



<div class="container">
  <%= yield %>
</div>

</body>

<footer>
  <div class="container">
    Author: Mohamed El Aazioui
  </div>
</footer>
</html>