config/routes.rb
Rails.application.routes.draw do

  resources :cards

  resources :bankers

  resources :branches

  root 'welcome#index'

  get '/agencies' => 'welcome#agencies'

  get '/dashboard' => 'welcome#dashboard'

  devise_for :clients, controllers: { sessions: 'clients/sessions'}

  resources :clients do
    resources :accounts
   end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :status
  belongs_to :category
  belongs_to :client

end

app/models/banker.rb
class Banker < ActiveRecord::Base
  belongs_to :branch
  has_many :clients

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :bankers

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :client
  belongs_to :account
  belongs_to :status
  belongs_to :type

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :accounts

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :accounts
  has_many :cards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accounts
  has_many :cards

end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :cards
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_client!
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  def index
    @accounts = current_client.accounts
    render_with_protection @accounts.to_json
  end

  def show
    render_with_protection @account.to_json
  end

  def new
    @account = Account.new
    render_with_protection @account.json

  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.save
    render_with_protection @account

  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end


  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:beginDate, :expiryDate, :saldo, :rate, :client_id, :status_id, :category_id)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_filter  :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def render_with_protection(json_content, parameters = {})
    render parameters.merge(content_type: 'application/json', text: "\n" + json_content)
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |c|
      c.permit(:email, :password, :password_confirmation, :firstName, :lastName, :street, :streetNr, :zipCode, :city, :birthDate, :birthPlace, :socialSecurityNumber, :nationality, :mobileNumber)
    end
  end
end

app/controllers/bankers_controller.rb
class BankersController < ApplicationController
  before_action :set_banker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bankers = Banker.all
    respond_with(@bankers)
  end

  def show
    respond_with(@banker)
  end

  def new
    @banker = Banker.new
    respond_with(@banker)
  end

  def edit
  end

  def create
    @banker = Banker.new(banker_params)
    @banker.save
    respond_with(@banker)
  end

  def update
    @banker.update(banker_params)
    respond_with(@banker)
  end

  def destroy
    @banker.destroy
    respond_with(@banker)
  end

  private
    def set_banker
      @banker = Banker.find(params[:id])
    end

    def banker_params
      params.require(:banker).permit(:firstName, :lastName, :phoneNumber, :emailAddress, :branch_id)
    end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  def index
    @branches = Branch.all
    render_with_protection @branches.to_json
  end

  def show
    respond_with(@branch)
  end

  def new
    @branch = Branch.new
    respond_with(@branch)
  end

  def edit
  end

  def create
    @branch = Branch.new(branch_params)
    @branch.save
    respond_with(@branch)
  end

  def update
    @branch.update(branch_params)
    respond_with(@branch)
  end

  def destroy
    @branch.destroy
    respond_with(@branch)
  end


  private
    def set_branch
      @branch = Branch.find(params[:id])
    end

    def branch_params
      params.require(:branch).permit(:name, :street, :streetNr, :zipCode, :city)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cards = Card.all
    respond_with(@cards)
  end

  def show
    respond_with(@card)
  end

  def new
    @card = Card.new
    respond_with(@card)
  end

  def edit
  end

  def create
    @card = Card.new(card_params)
    @card.save
    respond_with(@card)
  end

  def update
    @card.update(card_params)
    respond_with(@card)
  end

  def destroy
    @card.destroy
    respond_with(@card)
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:expiryDate, :managingCompany, :saldo, :limit, :client_id, :account_id, :status_id, :type_id)
    end
end

app/controllers/clients/passwords_controller.rb
class Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/clients/sessions_controller.rb
class Clients::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end



end

app/controllers/clients/unlocks_controller.rb
class Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_client!, except: [:index, :agencies]


  def index
  end

  def agencies
  end

  def dashboard
  end

  private
  def choose_layout
    client_signed_in? ? 'angular' : 'application'
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bankers_helper.rb
module BankersHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beginDate %><br>
    <%= f.date_select :beginDate %>
  </div>
  <div class="field">
    <%= f.label :expiryDate %><br>
    <%= f.date_select :expiryDate %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldo %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Begindate</th>
      <th>Expirydate</th>
      <th>Saldo</th>
      <th>Rate</th>
      <th>Client</th>
      <th>Status</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.beginDate %></td>
        <td><%= account.expiryDate %></td>
        <td><%= account.saldo %></td>
        <td><%= account.rate %></td>
        <td><%= account.client_id %></td>
        <td><%= account.status_id %></td>
        <td><%= account.category_id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Begindate:</strong>
  <%= @account.beginDate %>
</p>

<p>
  <strong>Expirydate:</strong>
  <%= @account.expiryDate %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @account.saldo %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @account.rate %>
</p>

<p>
  <strong>Client:</strong>
  <%= @account.client_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account.status_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @account.category_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/bankers/_form.html.erb
<%= form_for(@banker) do |f| %>
  <% if @banker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banker.errors.count, "error") %> prohibited this banker from being saved:</h2>

      <ul>
      <% @banker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :emailAddress %><br>
    <%= f.text_field :emailAddress %>
  </div>
  <div class="field">
    <%= f.label :branch_id %><br>
    <%= f.number_field :branch_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bankers/edit.html.erb
<h1>Editing banker</h1>

<%= render 'form' %>

<%= link_to 'Show', @banker %> |
<%= link_to 'Back', bankers_path %>

app/views/bankers/index.html.erb
<h1>Listing bankers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phonenumber</th>
      <th>Emailaddress</th>
      <th>Branch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bankers.each do |banker| %>
      <tr>
        <td><%= banker.firstName %></td>
        <td><%= banker.lastName %></td>
        <td><%= banker.phoneNumber %></td>
        <td><%= banker.emailAddress %></td>
        <td><%= banker.branch_id %></td>
        <td><%= link_to 'Show', banker %></td>
        <td><%= link_to 'Edit', edit_banker_path(banker) %></td>
        <td><%= link_to 'Destroy', banker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banker', new_banker_path %>

app/views/bankers/new.html.erb
<h1>New banker</h1>

<%= render 'form' %>

<%= link_to 'Back', bankers_path %>

app/views/bankers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @banker.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @banker.lastName %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @banker.phoneNumber %>
</p>

<p>
  <strong>Emailaddress:</strong>
  <%= @banker.emailAddress %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @banker.branch_id %>
</p>

<%= link_to 'Edit', edit_banker_path(@banker) %> |
<%= link_to 'Back', bankers_path %>

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :streetNr %><br>
    <%= f.text_field :streetNr %>
  </div>
  <div class="field">
    <%= f.label :zipCode %><br>
    <%= f.text_field :zipCode %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Listing branches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Streetnr</th>
      <th>Zipcode</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.street %></td>
        <td><%= branch.streetNr %></td>
        <td><%= branch.zipCode %></td>
        <td><%= branch.city %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @branch.street %>
</p>

<p>
  <strong>Streetnr:</strong>
  <%= @branch.streetNr %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @branch.zipCode %>
</p>

<p>
  <strong>City:</strong>
  <%= @branch.city %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expiryDate %><br>
    <%= f.date_select :expiryDate %>
  </div>
  <div class="field">
    <%= f.label :managingCompany %><br>
    <%= f.text_field :managingCompany %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldo %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.text_field :limit %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th>Expirydate</th>
      <th>Managingcompany</th>
      <th>Saldo</th>
      <th>Limit</th>
      <th>Client</th>
      <th>Account</th>
      <th>Status</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.expiryDate %></td>
        <td><%= card.managingCompany %></td>
        <td><%= card.saldo %></td>
        <td><%= card.limit %></td>
        <td><%= card.client_id %></td>
        <td><%= card.account_id %></td>
        <td><%= card.status_id %></td>
        <td><%= card.type_id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expirydate:</strong>
  <%= @card.expiryDate %>
</p>

<p>
  <strong>Managingcompany:</strong>
  <%= @card.managingCompany %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @card.saldo %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @card.limit %>
</p>

<p>
  <strong>Client:</strong>
  <%= @card.client_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @card.account_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @card.status_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @card.type_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>